"""add installment fields to transaction

Revision ID: b5f447bf6707
Revises: 315bcd1a1c9f
Create Date: 2026-09-19 20:24:42.913479

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b5f447bf6707"
down_revision: str | Sequence[str] | None = "315bcd1a1c9f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("transaction", sa.Column("installment_id", sa.Uuid(), nullable=True))
    op.add_column(
        "transaction", sa.Column("installment_number", sa.Integer(), nullable=True)
    )
    op.add_column(
        "transaction", sa.Column("total_installments", sa.Integer(), nullable=True)
    )
    op.add_column(
        "transaction",
        sa.Column("total_amount", sa.Numeric(precision=14, scale=2), nullable=True),
    )
    op.create_index(
        op.f("ix_transaction_installment_id"),
        "transaction",
        ["installment_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_transaction_installment_id"), table_name="transaction")
    op.drop_column("transaction", "total_amount")
    op.drop_column("transaction", "total_installments")
    op.drop_column("transaction", "installment_number")
    op.drop_column("transaction", "installment_id")
    # ### end Alembic commands ###
