"""create user table and add user_id to tables

Revision ID: 31447550d1c8
Revises: 07ee0dacb9a3
Create Date: 2026-10-03 13:57:19.766740

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "31447550d1c8"
down_revision: str | Sequence[str] | None = "07ee0dacb9a3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # 1. Create user table
    op.create_table(
        "user",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
        sa.Column(
            "email", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.Column(
            "username", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False
        ),
        sa.Column(
            "password_hash", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True
        ),
        sa.Column(
            "auth_provider", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False
        ),
        sa.Column(
            "google_id", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True
        ),
        sa.Column(
            "avatar_url", sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_approved", sa.Boolean(), nullable=False),
        sa.Column("role", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=True)
    op.create_index(op.f("ix_user_google_id"), "user", ["google_id"], unique=True)
    op.create_index(op.f("ix_user_username"), "user", ["username"], unique=True)

    # 2. Insert default admin user for existing data
    import uuid

    admin_id = uuid.uuid4()
    op.execute(
        sa.text(
            f'INSERT INTO "user" (id, name, email, username, auth_provider, is_active, is_approved, role, created_at, updated_at) '
            f"VALUES ('{admin_id}', 'Administrador', 'admin@local.dev', 'admin', 'local', true, true, 'admin', NOW(), NOW()) "
            f"ON CONFLICT DO NOTHING"
        )
    )

    # 3. Add user_id as nullable first, populate with admin_id, then set NOT NULL
    for tbl in ["account", "budget", "category", "transaction"]:
        op.add_column(tbl, sa.Column("user_id", sa.Uuid(), nullable=True))
        op.execute(
            sa.text(
                f'UPDATE "{tbl}" SET user_id = (SELECT id FROM "user" ORDER BY created_at ASC LIMIT 1) WHERE user_id IS NULL'
            )
        )
        op.alter_column(tbl, "user_id", nullable=False)

    # 4. Indexes & constraints
    op.create_index(op.f("ix_account_user_id"), "account", ["user_id"], unique=False)
    op.create_foreign_key(
        "fk_account_user_id", "account", "user", ["user_id"], ["id"], ondelete="CASCADE"
    )

    op.drop_constraint("uq_budget_category_period", "budget", type_="unique")
    op.create_index(op.f("ix_budget_user_id"), "budget", ["user_id"], unique=False)
    op.create_unique_constraint(
        "uq_budget_user_category_period",
        "budget",
        ["user_id", "category_id", "month", "year"],
    )
    op.create_foreign_key(
        "fk_budget_user_id", "budget", "user", ["user_id"], ["id"], ondelete="CASCADE"
    )

    op.drop_index(op.f("ix_category_name"), table_name="category")
    op.create_index(op.f("ix_category_name"), "category", ["name"], unique=False)
    op.create_index(op.f("ix_category_user_id"), "category", ["user_id"], unique=False)
    op.create_unique_constraint(
        "uq_category_user_name", "category", ["user_id", "name"]
    )
    op.create_foreign_key(
        "fk_category_user_id",
        "category",
        "user",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )

    op.create_index(
        op.f("ix_transaction_user_id"), "transaction", ["user_id"], unique=False
    )
    op.create_foreign_key(
        "fk_transaction_user_id",
        "transaction",
        "user",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint("fk_transaction_user_id", "transaction", type_="foreignkey")
    op.drop_index(op.f("ix_transaction_user_id"), table_name="transaction")
    op.drop_column("transaction", "user_id")
    op.drop_constraint("fk_category_user_id", "category", type_="foreignkey")
    op.drop_constraint("uq_category_user_name", "category", type_="unique")
    op.drop_index(op.f("ix_category_user_id"), table_name="category")
    op.drop_index(op.f("ix_category_name"), table_name="category")
    op.create_index(op.f("ix_category_name"), "category", ["name"], unique=True)
    op.drop_column("category", "user_id")
    op.drop_constraint("fk_budget_user_id", "budget", type_="foreignkey")
    op.drop_constraint("uq_budget_user_category_period", "budget", type_="unique")
    op.drop_index(op.f("ix_budget_user_id"), table_name="budget")
    op.create_unique_constraint(
        op.f("uq_budget_category_period"),
        "budget",
        ["category_id", "month", "year"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("budget", "user_id")
    op.drop_constraint("fk_account_user_id", "account", type_="foreignkey")
    op.drop_index(op.f("ix_account_user_id"), table_name="account")
    op.drop_column("account", "user_id")
    op.drop_index(op.f("ix_user_username"), table_name="user")
    op.drop_index(op.f("ix_user_google_id"), table_name="user")
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.drop_table("user")
    # ### end Alembic commands ###
