"""create initial schema

Revision ID: 7e13925a5787
Revises:
Create Date: 2026-09-19 18:55:16.390012

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7e13925a5787"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "account",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column(
            "account_type",
            sa.Enum(
                "CHECKING", "SAVINGS", "INVESTMENT", "CASH", name="account_type_enum"
            ),
            nullable=False,
        ),
        sa.Column("balance", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column(
            "currency", sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_account_name"), "account", ["name"], unique=False)
    op.create_table(
        "category",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column(
            "category_type",
            sa.Enum("INCOME", "EXPENSE", name="category_type_enum"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_category_name"), "category", ["name"], unique=True)
    op.create_table(
        "transaction",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column(
            "transaction_type",
            sa.Enum("INCOME", "EXPENSE", "TRANSFER", name="transaction_type_enum"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("CLEARED", "PENDING", name="transaction_status_enum"),
            nullable=False,
        ),
        sa.Column("transaction_date", sa.DateTime(), nullable=False),
        sa.Column(
            "description", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("source_account_id", sa.Uuid(), nullable=False),
        sa.Column("destination_account_id", sa.Uuid(), nullable=True),
        sa.Column("category_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(["category_id"], ["category.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["destination_account_id"], ["account.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["source_account_id"], ["account.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_transaction_category_id"), "transaction", ["category_id"], unique=False
    )
    op.create_index(
        op.f("ix_transaction_destination_account_id"),
        "transaction",
        ["destination_account_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_transaction_source_account_id"),
        "transaction",
        ["source_account_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_transaction_source_account_id"), table_name="transaction")
    op.drop_index(
        op.f("ix_transaction_destination_account_id"), table_name="transaction"
    )
    op.drop_index(op.f("ix_transaction_category_id"), table_name="transaction")
    op.drop_table("transaction")
    op.drop_index(op.f("ix_category_name"), table_name="category")
    op.drop_table("category")
    op.drop_index(op.f("ix_account_name"), table_name="account")
    op.drop_table("account")
    # ### end Alembic commands ###
