"""create budget table

Revision ID: 315bcd1a1c9f
Revises: 7e13925a5787
Create Date: 2026-09-19 20:08:37.738712

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "315bcd1a1c9f"
down_revision: str | Sequence[str] | None = "7e13925a5787"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "budget",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("category_id", sa.Uuid(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("month", sa.Integer(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["category_id"], ["category.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "category_id", "month", "year", name="uq_budget_category_period"
        ),
    )
    op.create_index(
        op.f("ix_budget_category_id"), "budget", ["category_id"], unique=False
    )
    op.create_index(op.f("ix_budget_month"), "budget", ["month"], unique=False)
    op.create_index(op.f("ix_budget_year"), "budget", ["year"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_budget_year"), table_name="budget")
    op.drop_index(op.f("ix_budget_month"), table_name="budget")
    op.drop_index(op.f("ix_budget_category_id"), table_name="budget")
    op.drop_table("budget")
    # ### end Alembic commands ###
