name: Deploy Wiki

on:
  push:
    branches:
      - main
    paths:
      - 'wiki/**'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy-wiki:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy to GitHub Wiki
        uses: Andrew-Chen-Wang/github-wiki-action@v4
        with:
          strategy: clone
          path: wiki/
        env:
          WIKI_ACTION_TOKEN: ${{ secrets.GITHUB_TOKEN }}
